## Dependencies {#sec-dependencies}

Here it is welcome to acknowledge the existing sources that have been used in this project with locations, and name their initiators.
At best, present dependencies following what these projects provide as citation information.
But at least:

-   Initiators of the original project

-   URL of the original project


You may also cite projects that project is citing as dependencies or source, with the URL of other related projects, and link to projects that are using this project as a dependency. This correponds to the OKH metadata entries variants_of, drivation_of, and sub-thing_of.

These dependencies can be hardware or software projects, modular components, libraries, or frameworks.
You may indicate information on version compatibility.
You should explicitly state if dependencies are proprietary / closed source.

This may also be used to present other OSH projects

------------------------------------------------------------------------

**Sources**

@sec-open-next-work, @sec-journal-of-open-hardware, @sec-source-OKH
