## User Guides : Safety information {#sec-user-guides-safety-information}

Describe all relevant safety issues or references to a risk assessment if included (for example high voltage, chemical safety etc.). If appropriate, discuss the wider context of the use of the hardware and safety issues or risks that may arise in the use environment.
t may include more than one link if different assessments cover different aspects or making, operation, maintenance and disposal of the hardware.

OSH makers are not always formally trained engineers and may not be able to easily differentiate between dangerous and safe manipulations.

This does not need to be an exhaustive list of all risks associated with the thing, but a summary of the most important risks and hazards associated with making, using, maintaining or disposing of the hardware. Knowledge of such issues could influence the decision to make the thing.

------------------------------------------------------------------------

**Sources**

@sec-journal-of-open-hardware, @sec-source-turing, sec-source-OKH